import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/providers/store-provider";
import GlobalLoader from "@/components/GlobalLoader";
import { ConfirmProvider } from "@/components/ConfirmDialog";
import QueryProvider from "@/providers/QueryProvider";
// import { ToastProvider } from "@/components/Toaster";
import { Toaster } from "@/components/ui/sonner"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        {/* <ToastProvider> */}
        <QueryProvider>
          <StoreProvider>
            <ConfirmProvider>
              {children}
            </ConfirmProvider>
            <GlobalLoader />
          </StoreProvider>
        </QueryProvider>
        {/* </ToastProvider> */}
      </body>
    </html>
  );
}
